posts/urls.py
from django.conf.urls import url

from .import views


urlpatterns = [

    url(r'^(?P<pk>[0-9]+)/$', views.view_post, name='view_post'),
    url(r'^list/$', views.list_posts, name='list_posts'),
    url(r'^create/$', views.create_post, name='create_post'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_post, name='edit_post'),
]

pystagram/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login
from django.contrib.auth.views import logout


urlpatterns = [
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^photos/', include('photos.urls', namespace='photos')),
    url(r'^admin/', admin.site.urls),
    url(
        r'^login/$', login,
        {'template_name': 'login.html'}, name='login_url'
    ),
    url(
        r'^logout/$', logout,
        {'next_page': '/login/'}, name='logout_url'
    ),
]

posts/models.py
from django.db import models
from django.conf import settings

from photos.models import Photo


class Post(models.Model):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False)
    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.ForeignKey('Category')
    tags = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ForeignKey(Photo, null=True)

    def __str__(self):
        return '<Post {}:{}>'.format(self.pk, self.title[:8])


class Category(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<Category {}:{}>'.format(self.pk, self.name)


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<Tag {}:{}>'.format(self.pk, self.name)

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('category', 'title', 'content',  )

posts/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from django.core.paginator import Paginator
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from .forms import PostForm
from .models import Post
from photos.models import Photo


def list_posts(request):
    page = request.GET.get('page', 1)
    per_page = 5
    posts = Post.objects.order_by('created_at')
    pg = Paginator(posts, per_page)

    try:
        contents = pg.page(page)
    except PageNotAnInteger:
        contents = pg.page(1)
    except EmptyPage:
        contents = []

    for content in contents:
        print('content=', content)
        print('content.photo=', content.photo)

        if content.photo is not None:
            content.thumb_url = content.photo.thumb_url
        else:
            content.thumb_url = ''

    return render(request, 'list_posts.html', {'posts':contents, })


def view_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    photo_url = ''
    if post.photo is not None:
        photo = Photo.objects.get(pk=post.photo.pk)
        photo_url = photo.image_url

    return render(request, 'view_post.html', {'post':post, 'photo_url':photo_url})


def create_post(request):
    # if pk is not None:
    #     post = get_object_or_404
    #     form = PostForm(instance=post)
    if request.method == 'GET':
        form = PostForm()
        form.photo = Photo.objects.order_by('?').first()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            photo_pk = request.POST.get('photo')
            post.photo = Photo.objects.get(pk=photo_pk)
            post.save()
            return redirect('posts:view_post', pk=post.pk)

    return render(request, 'edit_post.html', 
        {'form':form})


def edit_post(request, pk):
    # FIXME: 기존의 post 내용이 수정되는게 아니라 새로운 post가 생성되는 문제가 있습니다
    if request.method == 'POST':
        return create_post(request)

    else:
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(instance=post)
        form.photo = post.photo
    
    return render(request, 'edit_post.html', {'form':form})

posts/templates/edit_post.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 수정{% endblock %}

{% block body %}

{% if messages %}
{% for message in messages %}
    <div class="alert{% if message.tags %} alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}{% endif %} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
        {{ message|safe|urlize|linebreaksbr }}
    </div>
{% endfor %}
{% endif %}

<p>
{{form.photo.pk}}
</p>

<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    
    {% if form.photo %}
    <p><img src="{{ form.photo.image_url }}" style="max-width:50%; height:auto;" /></p>
    {% else %}
    <p>사진이 없습니다.</p>
    {% endif %}

    {{ form.as_p }}

    <p>
        <input type="hidden" name="photo" value="{{form.photo.pk}}">
    </p>

    <p>
        {% bootstrap_button "저장" button_type="submit" button_class="btn-primary" %}
    </p>
</form>

{% endblock %}

posts/templates/list_posts.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 목록{% endblock %}
{% block body %}


{% for post in posts %}
    <div class="post_container">
        <h3> 
        <a href = "{% url 'posts:view_post' post.pk %}">
        {{post.title}}
        </a>
        </h3>
        
        <img src="{{post.thumb_url}}"/>
        
        {{post.content}}
    </div>
    
{% empty %}
<p> TODO: 첫 글을 쓰시겠습니까? </p>
{% endfor %}

{% bootstrap_pagination posts %}
{% endblock %}

posts/templates/view_post.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 보기: {{post.title}} {% endblock %}

{% block body %}

<div class="post_container">
    <h3 class="post_title">{{post.title}}</h3>

    
    {% if post.photo %}
    <p><img src="{{photo_url}}" style="max-width:50%; height:auto;" /></p>
    {% else %}
    <p>사진이 없습니다.</p>
    {% endif %}

    <div class ="post_content"><p>{{post.content}}</p></div>

    <div>
        <p><span>카테고리:</span>{{post.category.name}}</p>
        <p><span>작성일시:</span>{{post.created_at}}</p>
    </div>
</div>

<div>
    <p><a href="{% url 'posts:edit_post' post.pk %}"> 글 수정</a></p>
</div>

{% endblock %}