photos/urls.py
from django.conf.urls import url

from .import views

urlpatterns = [
    url(r'^import/$', views.import_photo, name='import_photo'),
    url(r'^search/$', views.search_photo, name='search_photo'),
    url(r'^list/$', views.list_photos, name='list_photos'),
    url(r'^delete/$', views.delete_photos, name='delete_photos'),
]

posts/urls.py
from django.conf.urls import url

from .import views


urlpatterns = [

    url(r'^(?P<pk>[0-9]+)/$', views.view_post, name='view_post'),
    url(r'^list/$', views.list_posts, name='list_posts'),
    url(r'^create/$', views.create_post, name='create_post'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_post, name='edit_post'),
]

pystagram/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login
from django.contrib.auth.views import logout


urlpatterns = [
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^photos/', include('photos.urls', namespace='photos')),
    url(r'^admin/', admin.site.urls),
    url(
        r'^login/$', login,
        {'template_name': 'login.html'}, name='login_url'
    ),
    url(
        r'^logout/$', logout,
        {'next_page': '/login/'}, name='logout_url'
    ),
]

templates/layout.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block page_title %}Pystagram {% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<div class="container">
<p>
<h1 class="blog_name">{pystagram}</h1>
<a href="{% url 'posts:create_post' %}" class="btn btn-primary">새 글</a>
<a href="{% url 'posts:list_posts' %}" class="btn btn-primary">글목록</a>
<a href="{% url 'photos:search_photo' %}" class="btn btn-primary">사진수집</a>
<a href="{% url 'photos:list_photos' %}" class="btn btn-primary">사진목록</a>
</p>

{% block header %} {% endblock %}
{% block body %} {% endblock %}

</div>
</body>
</html>